### ISSUE TITLE
Debug why new conversations errors out occasioanlly.

### ISSUE THREAD

**Issue by davetaz** [SAGE-RAI/EmbedJS-RAG-Frontend-ODI#48]

**Comment by athird** [comment]
I get this - is it relevant, @davetaz? 

POST /instances/66bdf719cf6a738f580cc555/conversations/create 500 80.744 ms - 46
Error in verifyConversationMiddleware: CastError: Cast to ObjectId failed for value "create" (type string) at path "_id" for model "Conversations"
    at SchemaObjectId.cast (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/schema/objectId.js:250:11)
    at SchemaType.applySetters (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/schemaType.js:1236:12)
    at SchemaType.castForQuery (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/schemaType.js:1653:17)
    at cast (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/cast.js:375:32)
    at Query.cast (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/query.js:4857:12)
    at Query._castConditions (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/query.js:2265:10)
    at model.Query._findOne (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/query.js:2585:8)
    at model.Query.exec (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/query.js:4401:80)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async verifyConversationMiddleware (file:///Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/middleware/auth.js:184:30) {
  stringValue: '"create"',
  messageFormat: undefined,
  kind: 'ObjectId',
  value: 'create',
  path: '_id',
  reason: BSONError: input must be a 24 character hex string, 12 byte Uint8Array, or an integer
      at new ObjectId (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/bson/lib/bson.cjs:2362:23)
      at castObjectId (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/cast/objectid.js:25:12)
      at SchemaObjectId.cast (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/schema/objectId.js:248:12)
      at SchemaType.applySetters (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/schemaType.js:1236:12)
      at SchemaType.castForQuery (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/schemaType.js:1653:17)
      at cast (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/cast.js:375:32)
      at Query.cast (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/query.js:4857:12)
      at Query._castConditions (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/query.js:2265:10)
      at model.Query._findOne (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/query.js:2585:8)
      at model.Query.exec (/Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/node_modules/mongoose/lib/query.js:4401:80)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async verifyConversationMiddleware (file:///Users/at6737/Work/Projects/SAGE-RAI/Software/EmbedJS-RAG-Frontend-ODI/middleware/auth.js:184:30),
  valueType: 'string'
}

**Comment by athird** [comment]
@davetaz The commit 997297d1bfcdcef61a73743b73de5ead52148fee got rid of the above error, don't know if the original issue is more than this. I'm not sure if this is the right fix - I've added 'setActiveInstance' to each of the conversation routes, because it was failing with req.ragApplication being undefined, but I don't know if it's necessary to do this for all those routes. 

I think it might be, but please check!

**Comment by davetaz** [comment]
I think It was all to do with setActive instance as I now don't get the errors. Going to close for now.

**Comment by kwartengj** [comment]
I debugged the "Please send a message." error, which was mainly triggered by whitespace. The .trim() method should handle it unless there might have been other triggers. It seems to be working fine now, and I haven't encountered the issue since last night. I'll continue to monitor it...
